version: "3.9"

services:

  audio_processing_container:
    container_name: audio_processing
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/src
    ports:
      - 8888:8888
    working_dir: /src/model_processing
    runtime: nvidia